# Generated by Django 3.1.13 on 2021-09-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink_post', to='posts.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Drink',
                'verbose_name_plural': 'Drinks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classic', models.BooleanField(default=False, verbose_name='Classic Drink')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated time')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='drinks.drink', verbose_name='Drink')),
            ],
            options={
                'verbose_name': 'Cocktail',
                'verbose_name_plural': 'Cocktails',
                'ordering': ('-created_at',),
            },
        ),
    ]
