# Generated by Django 3.1.13 on 2021-09-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='post',
            new_name='drink',
        ),
    ]
