# Generated by Django 3.1.13 on 2021-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20210930_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
