# Generated by Django 3.1.13 on 2021-09-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts', verbose_name='First Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts', verbose_name='Second Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts', verbose_name='Third Image'),
        ),
    ]
